# src/main/resources/application.yml

spring:
  # 通过修改这里的 active 值来切换环境配置 (例如: local, server)
  profiles:
    active: docker # 默认激活本地环境，你可以根据需要修改为 server
  application:
    name: myweb_backend # 应用名称
  servlet:
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size}
      max-request-size: ${spring.servlet.multipart.max-request-size}
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  data:
    redis:
      host: ${spring.data.redis.host}
      port: 6379
      database: 0
  cache:
    type: redis
    redis:
      time-to-live: 3600s #  3600 秒

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: ${mybatis.configuration.log-impl}
  mapper-locations: classpath:com/example/mapper/*.xml

blog_image:
  upload-dir: ${blog_image.upload-dir}
  image-url: ${blog_image.image-url}
  base-url: ${blog_image.base-url}

# 通用的日志格式和默认的根日志级别
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${logging.level.root}
    com.example: ${logging.level.com.example}
  file:
    name: ${logging.file.name}