# src/main/resources/application-server.yml
# 在服务器上通过docker部署
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/myweb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai # 服务器数据库连接URL
    username: blogadmin # 服务器数据库用户名
    password: Gyt2003@GYTsecure # 服务器数据库密码
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    redis:
      host: redis
      port: 6379
      database: 0

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # MyBatis日志实现 (如果服务器需要特定的，可以在这里配置)

blog_image:
  upload-dir: /opt/myweb_backend_blog_imgs/ # 服务器图片上传物理路径
  image-url: /images/
  base-url: http://8.153.79.69 # 服务器图片访问前缀URL

# 服务器特定日志配置
logging:
  level:
    root: info
    com.example: info # 服务器上 com.example 包使用 info 级别
  file:
    name: /var/log/myweb_backend/server-app.log # 服务器日志文件路径